version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.code.findbugs:annotations
    versions:
    - "< 3.0.2, >= 3.0.1u1.a"
  - dependency-name: com.google.code.findbugs:annotations
    versions:
    - "< 3.0.2, >= 3.0.1u2.a"
  - dependency-name: org.jetbrains.kotlin:kotlin-test
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-test-junit
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: junit:junit
    versions:
    - 4.13.1
