on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: gradle check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: gradlew check
        run: 'docker run -e "HOSTUID=`id -u`"
             -e "HOSTGID=`id -g`"
             -v "`pwd`:/work"
             -v "$HOME:/home/hostuser"
             wtanaka/alpine-37-uid-openjdk8-gradle-git
             ./gradlew check'
#before_install:
#- openssl aes-256-cbc -K $encrypted_693767ad98dc_key -iv $encrypted_693767ad98dc_iv -in sec.pgp.enc -out sec.gpg -d
#deploy:
#- provider: script
#  script: git fetch --all; ./gradlew bintrayUpload uploadArchives closeAndReleaseRepository
#  skip_cleanup: true
#env:
#  global:
#  - secure: cUq3yNlqL72XtZx54aGjSRI6uo3BTUOcnV1luqhjFdGQNQf8ZOWcjNw42a9q/5dWurO2UNCQZsonL8uE2Y9gCONlDKh7NWmLslR4WYiyYgtHzXyla/5x3UKC92omLXGdCrZcKYu1n0tE00aGBRlExFb4MJE5R7gqj7YTzKgSOmYAvV0YUyKX2YogCyBwZTty86hApq+qDOp1QZA0EUi+iqGeVfkVLfewQLnZNaSM/0bqZANNRDVy8DfkqnDnrMtW2w21VfGBmCE+QsqROrVouf6/NQZzHvQdTqBtwTHYdDLBk+ACEmoBnjfHkUSXHwBxZP8tyknMWFPyZIDA/Rkdhb0Pjg1eJXcZ/c3QRqyjPxte7YVO73TKmy7UV2YECUcYKBnaHVxyZlFSbxzrBObXGCV0npD54z7d0UusoVzIZlmcPB5ZWc8DSUe/MFksmmwti6beFj/D/i0ljA40RtpjjXwTHVvmpFCtBKfnGEgghNgHkIN2iVwBr0evSdZV3Q6iILwOGcJZcIvUwJ39H51a8P5A3CELJTL4rVIYpgq+SngGrGa7w8xcic7TlrmcZ4K9W6pKAsZqcAORxmuxwX9PwzqvyVXOcEqijhuWqCsWzr0gLcuBMjf/7NuVcqYU+a6ABvDhO8cuxoWnrP88GayUQ4s/6d0IZk+bbfxdFXy5zvA=
#  - secure: D/izPVzIYAtlojtm6Q+q3wABTYXvTEQnwkj+RGSiOYa/FkHyyS+VCNJ3PG0ONNN+h+kRCqVmthGOdRs/6ik8kHzj2Vh6iNXnMDvqcTYsAJc1clE/nUJt03tLfPUFDNoUDt26SoyNccG4/gkSw7lAa8mWYx0jHkdxj0115/XHwBMhkDJbTik6yIbs6rc6wZG2Akd5GrJkXtNIorKT/rv8pZDl6kC6UyrzwKMLz8TeIYGvz+DMhsfBJ8u+BEnyhWLV/ECtHgZ+STmjnNoY4AFGyN+f4j7aw6Eg9xpG5BXgP0sfaQq/yRk9fuWDcbdRM1HDfoX9ZnH/HRXgESAssxg0/RtMKhY6usS412SP27Q2Q8rsmc0AiqfcW5byKMYUoKEfKH3RrVIKfug9lK9Y4cY3v0c6uMQBtPHLpRJyQCP9FmrxzcAM8wxFEZ6rlPQpyviXPvS+9CfL4Ad7grg5CNpBiAfZrdctSkdAX5cbQzsMFO3I95Yi70Rib/U1YEFpbgFy+Jr2DQH+AWE1pl8IISgsb8APc/R6RWfTWHbBlXqYBvuMRwooyYJuTQ+3I2O0RqDSXhPOe1ht0KfsrFXghyKGKmG10cCZkIlIBe5UNB5AE6HtDCrpLpOsWm+WYmfnX2ITLpJAhVA2Zwwthytg6aGjf8xP0Nzs6T5sZpFTeDecjxQ=
